use_frameworks!

platform :ios, '9.0'

target 'ZHDoubleSlider_Example' do
  pod 'ZHDoubleSlider', :path => '../'

  target 'ZHDoubleSlider_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
